```{r load library, message=FALSE}
library(tidyverse)
library(kableExtra)
library(knitr)
library(leaflet)
library(tidytransit)
```
```{r use tidytrasit}

tokyo_gtfs <- read_gtfs('tokyo_trains.zip')
attach(tokyo_gtfs)
summary(tokyo_gtfs)
kable(head(tokyo_gtfs$stops))
```

```{r visualization on stops}
# visualize the stops
stop_maps = leaflet() %>%
  # Add CartoDB background map
  addProviderTiles("OpenStreetMap.Mapnik") %>%  
  # Add a marker for each stop
  addCircleMarkers(lng= ~ stop_lon, lat= ~stop_lat, 
                   data = tokyo_gtfs$stops, stroke = FALSE, 
                   fillOpacity = 5, radius = 3) 
stop_maps  # Show the map
```

```{r departure timetable}
# extract stop ids from the same station.
# different agency has different stop ids for the same station
stop_ids <- tokyo_gtfs$stops %>%
  filter(stop_name == '目黒') %>%
  select(stop_id)

# extract trip info and time from stop_time based on stop_id
departure <- stop_ids %>%
  inner_join(tokyo_gtfs$stop_times %>%
               select(trip_id, arrival_time,
                      departure_time, stop_id),
             by = "stop_id")

# add trip id
departure <- departure %>%
  left_join(tokyo_gtfs$trips %>%
              select(trip_id, route_id,
                     service_id, trip_headsign, direction_name),
            by = "trip_id")

# add route info from routes
departure <- departure %>%
  left_join(tokyo_gtfs$routes %>%
              select(route_id,
                     route_long_name),
            by = "route_id")

# right now service id has weekday and weekend mixed.
departure %>%
  select(route_long_name,
         trip_headsign,
         arrival_time) %>%
  arrange(arrival_time) %>%
  knitr::kable()

weekday <- departure %>%
  filter(grepl("Weekday", service_id, fixed = TRUE))

weekday_schedule <- weekday %>%
  select(route_long_name,
         trip_headsign,
         arrival_time) %>%
  arrange(arrival_time)

knitr::kable(weekday_schedule)

# output for weekday schedule
data.table::fwrite(weekday_schedule, "weekday schedule.csv")

weekend <- departure %>%
  filter(!grepl("Weekday", service_id, fixed = TRUE))

weekend_schedule <- weekend %>%
  select(route_long_name,
         trip_headsign,
         arrival_time) %>%
  arrange(arrival_time)

knitr::kable(weekend_schedule)

# output for weekend schedule
data.table::fwrite(weekend_schedule, "weekend schedule.csv")
```
